version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  node-app:
    build:
      context: ./node-app
    ports:
      - "3000:3000"

volumes:
  jenkins_home:

