apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
spec:
  type: NodePort
  selector:
    app: jenkins-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000

