name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: github_actions_cicd

    - name: Run tests
      run: npm test
      working-directory: github_actions_cicd

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t joshini1212/github-cicd:latest github_actions_cicd
        docker push joshini1212/github-cicd:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes_assessment/deployment.yaml
        kubectl apply -f kubernetes_assessment/service.yaml

